### PR TITLE
Only install and configure docker and JRE

### PR DESCRIPTION
**Pull request by mattface**
As builds are going to be in docker, remove all the package and mirrors configuration

### CODE REVIEW

**Comment by khilman** [comment]
IMO, adding of new builders (azure) should be a separate commit.  It's not related to $SUBJECT

**Comment by mattface** [comment]
I will split the builders out. The JRE stuff is just a rename, they were already being installed. I could have just removed all the other packages, but that mean "packages.yml" seemed a bit misnamed.

**Comment by khilman** [comment]
So a related question, do we still need a JRE on the builders?
The subject suggests (and I assumed) we only needed docker.

**Comment by mattface** [comment]
You need it to run the jenkins slave

**Pull request merged**
